name: ransomwatch

on:
# schedule:
#    - cron: '0 */1 * * *'
#  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

# to consider: the use of action jobs to breakout each task
# https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs

jobs:
  torsocks-job:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    services:
      torproxy:
        image: ghcr.io/joshhighet/torsocc:latest
        ports:
        - 9050:9050
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: run scraper
        run: |
          python3 ransomwatch.py scrape
      - name: run parser
        #env: 
          #DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          #DISCORD_WEBHOOK_2: ${{ secrets.DISCORD_WEBHOOK_2 }}
         # MS_TEAMS_WEBHOOK: ${{ secrets.MS_TEAMS_WEBHOOK }}
#          X_CONSUMER_KEY: ${{ secrets.X_CONSUMER_KEY }}
         # X_CONSUMER_SECRET: ${{ secrets.X_CONSUMER_SECRET }}
         # X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
        #  X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        run: |
          python3 ransomwatch.py parse
      - name: generate markdown & graphs for docsify
        run: |
          python3 ransomwatch.py markdown
      - name: generate kv groups for analytics
        run: |
          python3 assets/groups-kv.py
      - name: save changes
        # git config --global user.email "joshhighet@users.noreply.github.com"
        # git config --global user.name "josh"
        run: |  
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit --all --message "𝚌𝚛𝚘𝚗𝚋𝚘𝚝" || echo "no changes to commit"
          git push
